# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.

name: melpazoid
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jcs090218/setup-emacs@master
      with:
        version: 29.4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        git clone --depth 1 https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid
    - name: Run
      env:
        LOCAL_REPO: ${{ github.workspace }}
        # RECIPE is your recipe as written for MELPA:
        RECIPE: (jsonp :fetcher github :repo "joshbax189/jsonp-el")
        # set this to false (or remove it) if the package isn't on MELPA:
        EXIST_OK: false
      run: echo $GITHUB_REF && make -C ~/melpazoid
